CREATE TABLE imoveis.imoveis (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  valor VARCHAR(255) DEFAULT NULL,
  cep VARCHAR(255) DEFAULT NULL,
  informacoes VARCHAR(5000) DEFAULT NULL,
  imagem VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;