--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/03/2021 15:54:26
-- Server version: 10.4.17
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO imoveis.imoveis(id, valor, cep, informacoes, imagem) VALUES
(1, '50', '01001000', 'fasfasdfasdfasdfasdf', 'imagensImoveis/ASDF.jpg'),
(3, '1500', '01010000', 'Casa com 3 quartos, 2 banheiros, cozinha e sala de jantar.', 'imagensImoveis/download (2).jpg'),
(4, '2000', '40020025', 'Casa com 6 quartos, 3 banheiros, cozinha e sala de jantar.', 'imagensImoveis/download (3).jpg'),
(5, '2500', '52050500', 'Casa com 6 quartos, 5 banheiros, cozinha e sala de jantar.', 'imagensImoveis/download.jpg');